[window]
decorations = "Full"

[font]
normal.family = "0xProto Nerd Font"
bold.family = "0xProto Nerd Font"
italic.family = "0xProto Nerd Font"
bold_italic.family = "0xProto Nerd Font"
size = 14.0

[colors.primary]
background = '#212121'
foreground = '#B0BEC5'

[colors.normal]
black   = '#000000'
red     = '#F07178'
green   = '#C3E88D'
yellow  = '#FFCB6B'
blue    = '#82AAFF'
magenta = '#a36ac7'
cyan    = '#89DDFF'
white   = '#EEFFFF'

[colors.bright]
black   = '#969896'
red     = '#cc342b'
green   = '#198844'
yellow  = '#fba922'
blue    = '#3971ed'
magenta = '#a36ac7'
cyan    = '#3971ed'
white   = '#ffffff'
